apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ooooak/auth
          env:
            - name: PG_CONN
              value: 'host=auth-pg-service user=postgress password=password dbname=postgress port=5432 sslmode=disable TimeZone=Asia/Kolkata'
            - name: JWT_KEY
              value: test
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
