apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-pg-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pg
  template:
    metadata:
      labels:
        app: auth-pg
    spec:
      containers:
        - name: auth-pg
          image: postgres
          env:
            - name: POSTGRES_USER
              value: 'postgress'
            - name: POSTGRES_PASSWORD
              value: 'password'
            - name: POSTGRES_DB
              value: 'postgress'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-pg-service
spec:
  selector:
    app: auth-pg
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432